### ISSUE TITLE
Configurable URL base path

### ISSUE THREAD

**Issue by atmaniak** [inbucket/inbucket#107]
We can't find a way to use inbucket behind a nginx proxy as a subdirectory since all path are hard-coded to work as root directory.

Do you have any idea how to do such a thing ?

It could be nice to have something like this :
http://some.domain/inbucket/

**Comment by jhillyerd** [comment]
You are correct, there is no way to do this currently.  I can look at supporting this after the UI rewrite is done.

**Comment by mmrath** [comment]
@jhillyerd it would be nice to get this done. I can probably do the golang part, but I have no idea of elm.

**Comment by jhillyerd** [comment]
When I moved this to the backlog, I didn't realize it would take this long to finish the 3.0 beta...  Off the top of my head, I'm not exactly sure how much work this would be.  But I think we can make it part of 3.0 instead of waiting for a follow-up release.

The way we bootstrap config from Go to Elm is via this JSON pair, stuffing it into a cookie (hack!), that way no API calls (and URI paths) are involved during UI startup.

- https://github.com/inbucket/inbucket/blob/master/pkg/server/web/app_json.go
- https://github.com/inbucket/inbucket/blob/master/ui/src/Data/AppConfig.elm

I'm not yet sure how we'd need to modify the Elm code to make use of this.  The nature of functional programming often requires things liked this to be plumbed through, as there is no easy way to get to a global configuration context.

**Comment by jhillyerd** [comment]
Note to self: AppConfig is stored in the Elm Session, it would make sense to have Session generate URLs for API calls.  Would also need Route to take some sort of base URI parameter.

**Comment by jhillyerd** [comment]
First step done, elm UI is aware of a base path and will use it for internal routing.  Next steps are to have inbucket backend support configuring it's base path, respect it for routing, pass it to elm.  Then elm will need to be updated to use the new path for API calls.

**Comment by jhillyerd** [comment]
Updated backend to accept a config parameter and prefix all the web UI & API routes in `feature/router` branch.

Next steps:

- [ ] Pass the configured prefix on to the Elm frontend so that it uses it.
- [ ] Update Elm->backend API calls to also use the new prefix.
- [ ] Add backend HTTP redirect from / to prefix/

**Comment by jhillyerd** [comment]
Alright, I think this is working now.  It ended up touching a lot of code, so I'd love it if someone could test with nginx or similar this prior to me cutting a new beta release.  It's available in docker via `inbucket/inbucket:latest` now.

**Comment by msylw** [comment]
Tried it with nginx as proxy, so far noticed no problems.

The only thing I had to tweak was nginx to correctly forward websocket requests:
```
            proxy_http_version 1.1;
            proxy_set_header    Upgrade            $http_upgrade;
            proxy_set_header    Connection         "upgrade";
```

**Comment by jhillyerd** [comment]
Awesome, thank you for testing.  I'll get a new beta out soon.
