### ISSUE TITLE
3.0 user interface feedback

### ISSUE THREAD

**Issue by jhillyerd** [inbucket/inbucket#137]
Please leave your kudos, comments and criticisms of the new 3.0 user interface here.  If it looks like a bug, please don't hesitate to open a new issue instead.

**Comment by alexizmailov** [comment]
I'm running Inbucket as a Docker image. Every time when it is restarted for whatever reason (mostly it's a bug in docker puppet module) - `monitor` tab clears out, although messages can be retrieved via pop or by accessing `recent emai boxes`. 

However, our testers send tons of emails from apps and recipient addresses are random so it's almost impossible to see those emails when Inbucket was restarted.

Since `config` tab can see the amount of stored emails, I think reinstating the list of received emails on `monitor` tab would be very convenient.

**Comment by jhillyerd** [comment]
Apologies for slow response, work has been very busy lately.

What you describe isn't a bug, currently by design but I am open to more feedback.  Given it's not new to v3.0, feel free to open a new issue on it.

1. Most of what you see in the monitor tab is actually being cached by your browser.  Only `INBUCKET_WEB_MONITORHISTORY` (default 30) are stored in server memory.  Restarting Inbucket will clear that.
2. Even the number of stored emails is calculated at runtime (they are counted during the retention scanner run), and won't be immediately available at server startup.

Given that your Inbucket isn't being shutdown cleanly, it might require some sort of rolling journal of received mail.  A periodic checkpoint may not run often enough.   One of my goals for Inbucket is to keep performance high, so this would require some more thought.
