### ISSUE TITLE
Monitor does not show old messages after restart

### ISSUE THREAD

**Issue by poblabs** [inbucket/inbucket#147]
Hi, I'm not sure if this is expected behavior or not. 

I have setup a volume to `/storage`, and used an environment variable for `INBUCKET_STORAGE_PARAMS="path:/storage"`. Everything works fine until I stop and start the container. Once I do that I no longer see messages on the monitor tab. 

On the Status tab, I do see the `Stored Messages` show the correct number of messages. When I open a mailbox, those messages are present too. So I know the volume is persisting correctly.

I'm treating the Monitor tab as the inbox of all inbox. Is it possible to have all the old messages display again on the Monitor tab after a container restart?

**Comment by poblabs** [comment]
I guess based on this comment - https://github.com/inbucket/inbucket/issues/54#issuecomment-318843203 - this is probably working by your design? 

If so; is it possible to have an "inbox of all inboxes" view somehow that will persist? Perhaps through another environment variable?

**Comment by jhillyerd** [comment]
Yes, there is a similar conversation on #137 - but glad to have a dedicated issue for it.  Here's a lightly edited copy of my previous response:

What you describe isn't a bug, currently by design but I am open to more feedback.

1. Most of what you see in the monitor tab is actually being cached by your browser.  Only `INBUCKET_WEB_MONITORHISTORY` (default 30) are stored in server memory.  Restarting Inbucket will clear that.
2. Even the number of stored emails is calculated at runtime (they are counted during the retention scanner run), and won't be immediately available at server startup.

Given that your Inbucket isn't being shutdown cleanly, it might require some sort of rolling journal of received mail.  A periodic checkpoint may not run often enough.   One of my goals for Inbucket is to keep performance high, so this would require some more thought.

**Comment by jhillyerd** [comment]
You may also find the feature added in #139 (available in current beta release) helpful, as it collapses all inbound emails to just their domain name and uses that as the mailbox.

There does seem to be enough interest in persisting the monitor log that I think it should be added in the future.

**Comment by poblabs** [comment]
I agree, the performance is why I'm using inbucket right now. I'll try out the beta release, maybe it'll satisfy what I'm looking for. 

On the idea of the Monitor, I think that's good too; to see new messages in real time as they arrive with the option to clear the log to get a fresh view in that moment.

Perhaps all that's needed is another menu item for the persistent messages that are stored? Unsure what that means to the websocket and the API though (I have very limited exposure to inbucket so far).

**Comment by poblabs** [comment]
Oh, I didn't realize I am running the beta already. So the beta is what I'm basing this request off of (having the unified inbox). 

`v3.0.0-beta2-1-g12802e9, built on 2019-09-17T15:56:26+0000`

I am noticing another issue with the Monitor and deleting a message. It doesn't delete it from the Monitor which results in a 404 when you click on it. I can open another issue on this for tracking if you want?

**Comment by jhillyerd** [comment]
In case it wasn't clear, you have to enable the unified domain inbox if you want to use it.

Yes, go ahead an open an issue for the deleted messages leading to 400s, that's something I'd like to fix eventually; and will be a precursor to live-updating mailbox content.

**Comment by poblabs** [comment]
Sorry, no it wasn't clear. I read the commit and see that now. I changed the mailboxnaming to `domain` (I had it at `full` before). Having the domain inbox open won't refresh automatically, right? Only Monitor does that? I'll try this out and see how it goes.

**Comment by jhillyerd** [comment]
Correct, no auto refresh on for the inbox page at this time.  The back end already supports it (for new messages), but the front end does not yet use it.
