### ISSUE TITLE
Future of the project

### ISSUE THREAD

**Issue by demisx** [inbucket/inbucket#159]
Hi,

This is an excellent project and we'd love to use it in our E2E tests. However, I am concerned that it hasn't been updated since 12/18. Is it still being maintained? What are the plans for the nearest future?

Thank you.

**Comment by jhillyerd** [comment]
Right now this repo uses git-flow, so master only has stable releases, which makes it look more dead than it really is.  The [develop](https://github.com/inbucket/inbucket/tree/develop) branch is where the pre-release code is.

That being said, I don't spend a great deal of time on Inbucket, and there are no other regular contributors - so the pace of development will remain slow.  If you aren't in need of many new features, Inbucket should be a relatively safe choice - Go has a strong backwards compatibility contract so it doesn't require any upkeep to continue compiling on new versions of the language.

As far as near future plans go: I'm slowly chipping away at completing the [UI refresh](https://github.com/inbucket/inbucket/projects/3) which turned out to be a much larger project than anticipated.  Once most of those tasks are complete, I'll release 3.0.0

**Comment by demisx** [comment]
@jhillyerd Thank you very much for your prompt and detail response. It really helps!

**Comment by jhillyerd** [comment]
Just released 3.0.0, and main branch will track development after #242 , closing this.
