### ISSUE TITLE
Incorrect service path in debian package

### ISSUE THREAD

**Issue by techsachin1** [inbucket/inbucket#363]
not able to install and configure on ubuntu
kindly share steps plz

**Comment by Kasztan404** [comment]
1. Download:

 wget https://github.com/inbucket/inbucket/releases/download/v3.1.0-beta1/inbucket_3.1.0-beta1_linux_amd64.deb

 

 2. Install:

 dpkg -i inbucket_3.1.0-beta1_linux_amd64.deb

 

 3. add to systemctl:

 systemctl enable inbucket

 

 4. start:

 systemctl start inbucket

 

 4. check for any problems:

 systemctl status inbucket

 

 in my case (invalid exec path):

● inbucket.service - Inbucket Disposable Email Service

   Loaded: loaded (/lib/systemd/system/inbucket.service; enabled; vendor preset: enabled)

   Active: failed (Result: exit-code) since Fri 2023-05-26 08:45:16 CEST; 7s ago

  Process: 567 ExecStartPre=/bin/mkdir -p /var/local/inbucket (code=exited, status=0/SUCCESS)

  Process: 568 ExecStartPre=/bin/chown daemon:daemon /var/local/inbucket (code=exited, status=0/SUCCESS)

  Process: 569 ExecStart=/usr/local/bin/inbucket (code=exited, status=203/EXEC)

 Main PID: 569 (code=exited, status=203/EXEC)

 

 > so I had to correct it (In my opinion it is bug):

 pico /lib/systemd/system/inbucket.service

 

 edit this:

 /usr/local/bin/inbucket

 

 to that:

 /usr/bin/inbucket


> save file

 

5. reload systemctl:

systemctl daemon-reload

systemctl start inbucket


6.check again:

systemctl status inbucket


now ok:

inbucket.service - Inbucket Disposable Email Service

   Loaded: loaded (/lib/systemd/system/inbucket.service; enabled; vendor preset: enabled)

   Active: active (running) since Fri 2023-05-26 08:47:16 CEST; 4s ago

  Process: 602 ExecStartPre=/bin/mkdir -p /var/local/inbucket (code=exited, status=0/SUCCESS)

  Process: 603 ExecStartPre=/bin/chown daemon:daemon /var/local/inbucket (code=exited, status=0/SUCCESS)

 Main PID: 604 (inbucket)

    Tasks: 9 (limit: 4698)

   Memory: 9.2M

   CGroup: /system.slice/inbucket.service

           └─604 /usr/bin/inbucket

**Comment by jhillyerd** [comment]
Tested after PR above.   inbucket deb installs and starts on Ubuntu server.  inbucket rpm installs and starts on Fedora server.  I'll keep this open until the next beta release.

**Comment by Kasztan404** [comment]
I've built from source and it's look good also on debian. Waiting for  release .deb package ;) good work!

**Comment by jhillyerd** [comment]
fix available in https://github.com/inbucket/inbucket/releases/tag/v3.1.0-beta2
