### ISSUE TITLE
Inbucket support AUTH LOGIN ?

### ISSUE THREAD

**Issue by cpanato** [inbucket/inbucket#62]
Hello

Inbucket support AUTH LOGIN as a authentication method?

thanks!

**Comment by jhillyerd** [comment]
Inbucket does not support any sort of SMTP AUTH or SSL/TLS at this point.

If it was to be implemented, it would likely accept any user/password combination - there is no plan to move towards a traditional authentication model.

**Comment by cpanato** [comment]
ok, thanks!

**Comment by MaxDiOrio** [comment]
Any thoughts on this?  This is getting to be a crucial component in testing third party utilities that send email.

**Comment by jhillyerd** [comment]
I haven't been doing much work on Inbucket lately; when I resume I will need to focus on completing the UI refresh, as there are a number of outstanding issues with it, before adding new features.

As a work around, you could probably place a traditional SMTP server (Postfix etc) in front of Inbucket, and have it use Inbucket as a smart relay.  Obviously you would lose some of the value of Inbucket's logging since Postfix would be the one interacting with the client.

**Comment by makarchuk** [comment]
I think I can tackle this one. 

Will it be good enough to support a single valid credentials pair provided in config? I think it'll work just fine for most usecases

**Comment by jhillyerd** [comment]
Awesome! A single credential sounds reasonable to me -- or just support any credential presented if possible, that's how our PO3 server works.  Folks that need more complicated setups can front Inbucket with another mailserver.
